/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface CampaignInterface extends Interface {
    getFunction(nameOrSignature: "donate" | "image" | "owner" | "recivedAmout" | "requireedAmouut" | "story" | "tittle"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "donated"): EventFragment;

    encodeFunctionData(functionFragment: 'donate', values?: undefined): string;
encodeFunctionData(functionFragment: 'image', values?: undefined): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'recivedAmout', values?: undefined): string;
encodeFunctionData(functionFragment: 'requireedAmouut', values?: undefined): string;
encodeFunctionData(functionFragment: 'story', values?: undefined): string;
encodeFunctionData(functionFragment: 'tittle', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'donate', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'image', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'recivedAmout', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'requireedAmouut', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'story', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'tittle', data: BytesLike): Result;
  }

  
    export namespace donatedEvent {
      export type InputTuple = [donar: AddressLike, amount: BigNumberish, timestamp: BigNumberish];
      export type OutputTuple = [donar: string, amount: bigint, timestamp: bigint];
      export interface OutputObject {donar: string, amount: bigint, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface Campaign extends BaseContract {
    
    connect(runner?: ContractRunner | null): Campaign;
    waitForDeployment(): Promise<this>;

    interface: CampaignInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    donate: TypedContractMethod<
      [],
      [void],
      'payable'
    >
    

    
    image: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    recivedAmout: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    requireedAmouut: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    story: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    tittle: TypedContractMethod<
      [],
      [string],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'donate'): TypedContractMethod<
      [],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'image'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'recivedAmout'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'requireedAmouut'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'story'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'tittle'): TypedContractMethod<
      [],
      [string],
      'view'
    >;

    getEvent(key: 'donated'): TypedContractEvent<donatedEvent.InputTuple, donatedEvent.OutputTuple, donatedEvent.OutputObject>;

    filters: {
      
      'donated(address,uint256,uint256)': TypedContractEvent<donatedEvent.InputTuple, donatedEvent.OutputTuple, donatedEvent.OutputObject>;
      donated: TypedContractEvent<donatedEvent.InputTuple, donatedEvent.OutputTuple, donatedEvent.OutputObject>;
    
    };
  }