/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface CampinfactoryInterface extends Interface {
    getFunction(nameOrSignature: "createcampain" | "deployedcampaigns"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "campainCreate"): EventFragment;

    encodeFunctionData(functionFragment: 'createcampain', values: [string, BigNumberish, string, string, string]): string;
encodeFunctionData(functionFragment: 'deployedcampaigns', values: [BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'createcampain', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'deployedcampaigns', data: BytesLike): Result;
  }

  
    export namespace campainCreateEvent {
      export type InputTuple = [title: string, requireAmount: BigNumberish, owner: AddressLike, campaignAddress: AddressLike, imgURI: string, timestamp: BigNumberish, category: string];
      export type OutputTuple = [title: string, requireAmount: bigint, owner: string, campaignAddress: string, imgURI: string, timestamp: bigint, category: string];
      export interface OutputObject {title: string, requireAmount: bigint, owner: string, campaignAddress: string, imgURI: string, timestamp: bigint, category: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface Campinfactory extends BaseContract {
    
    connect(runner?: ContractRunner | null): Campinfactory;
    waitForDeployment(): Promise<this>;

    interface: CampinfactoryInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    createcampain: TypedContractMethod<
      [campaignTitle: string, requireCamapinAmount: BigNumberish, imguRI: string, storyURI: string, category: string, ],
      [void],
      'nonpayable'
    >
    

    
    deployedcampaigns: TypedContractMethod<
      [arg0: BigNumberish, ],
      [string],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'createcampain'): TypedContractMethod<
      [campaignTitle: string, requireCamapinAmount: BigNumberish, imguRI: string, storyURI: string, category: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'deployedcampaigns'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [string],
      'view'
    >;

    getEvent(key: 'campainCreate'): TypedContractEvent<campainCreateEvent.InputTuple, campainCreateEvent.OutputTuple, campainCreateEvent.OutputObject>;

    filters: {
      
      'campainCreate(string,uint256,address,address,string,uint256,string)': TypedContractEvent<campainCreateEvent.InputTuple, campainCreateEvent.OutputTuple, campainCreateEvent.OutputObject>;
      campainCreate: TypedContractEvent<campainCreateEvent.InputTuple, campainCreateEvent.OutputTuple, campainCreateEvent.OutputObject>;
    
    };
  }