/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface CampaignFactoryInterface extends Interface {
    getFunction(nameOrSignature: "createCampaign" | "createcampain" | "deployedCampaigns" | "deployedcampaigns" | "getDeployedCampaigns"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "CampaignCreated"): EventFragment;

    encodeFunctionData(functionFragment: 'createCampaign', values: [string, BigNumberish, string, string, string]): string;
encodeFunctionData(functionFragment: 'createcampain', values: [string, BigNumberish, string, string, string]): string;
encodeFunctionData(functionFragment: 'deployedCampaigns', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'deployedcampaigns', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getDeployedCampaigns', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'createCampaign', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createcampain', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'deployedCampaigns', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'deployedcampaigns', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getDeployedCampaigns', data: BytesLike): Result;
  }

  
    export namespace CampaignCreatedEvent {
      export type InputTuple = [title: string, requiredAmount: BigNumberish, owner: AddressLike, campaignAddress: AddressLike, imgURI: string, timestamp: BigNumberish, category: string];
      export type OutputTuple = [title: string, requiredAmount: bigint, owner: string, campaignAddress: string, imgURI: string, timestamp: bigint, category: string];
      export interface OutputObject {title: string, requiredAmount: bigint, owner: string, campaignAddress: string, imgURI: string, timestamp: bigint, category: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface CampaignFactory extends BaseContract {
    
    connect(runner?: ContractRunner | null): CampaignFactory;
    waitForDeployment(): Promise<this>;

    interface: CampaignFactoryInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    createCampaign: TypedContractMethod<
      [campaignTitle: string, requiredCampaignAmount: BigNumberish, imgURI: string, storyURI: string, category: string, ],
      [string],
      'nonpayable'
    >
    

    
    createcampain: TypedContractMethod<
      [campaignTitle: string, requireCamapinAmount: BigNumberish, imguRI: string, storyURI: string, category: string, ],
      [string],
      'nonpayable'
    >
    

    
    deployedCampaigns: TypedContractMethod<
      [arg0: BigNumberish, ],
      [string],
      'view'
    >
    

    
    deployedcampaigns: TypedContractMethod<
      [index: BigNumberish, ],
      [string],
      'view'
    >
    

    
    getDeployedCampaigns: TypedContractMethod<
      [],
      [string[]],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'createCampaign'): TypedContractMethod<
      [campaignTitle: string, requiredCampaignAmount: BigNumberish, imgURI: string, storyURI: string, category: string, ],
      [string],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'createcampain'): TypedContractMethod<
      [campaignTitle: string, requireCamapinAmount: BigNumberish, imguRI: string, storyURI: string, category: string, ],
      [string],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'deployedCampaigns'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'deployedcampaigns'): TypedContractMethod<
      [index: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getDeployedCampaigns'): TypedContractMethod<
      [],
      [string[]],
      'view'
    >;

    getEvent(key: 'CampaignCreated'): TypedContractEvent<CampaignCreatedEvent.InputTuple, CampaignCreatedEvent.OutputTuple, CampaignCreatedEvent.OutputObject>;

    filters: {
      
      'CampaignCreated(string,uint256,address,address,string,uint256,string)': TypedContractEvent<CampaignCreatedEvent.InputTuple, CampaignCreatedEvent.OutputTuple, CampaignCreatedEvent.OutputObject>;
      CampaignCreated: TypedContractEvent<CampaignCreatedEvent.InputTuple, CampaignCreatedEvent.OutputTuple, CampaignCreatedEvent.OutputObject>;
    
    };
  }